# Generated by Django 4.1 on 2022-09-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPLPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('team', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('points_per_game', models.FloatField()),
                ('selected_by_percent', models.FloatField()),
                ('now_cost', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
        ),
    ]
