# Generated by Django 4.1 on 2022-09-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eplplayer',
            name='points_per_game',
            field=models.IntegerField(),
        ),
    ]
